[project]
name = "desafio-valcann"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pytest>=8.4.2",
    "sqlalchemy>=2.0.43",
    "taskipy>=1.14.1",
]
